### ISSUE TITLE
Size of PCB for SMT assembly

### ISSUE THREAD

**Issue by cereyanli** [forestcaver/Analog-Voice#1]
Hello 

Thanks for this nice design AJH_Wasp

I am trying to order pcb and smt assembly through JLCPCB but I stucked as width of your PCB 19mm but JLCPCB min. requirement for SMT assembly is 20mm.

Is there anything you or I can do ?

Thanks

**Comment by forestcaver** [comment]
You can easily make it larger! (All the design files are there - I did that when I did a small pcba run...)

**Comment by cereyanli** [comment]
Hi 
I am quite a newbie with PCB Design and process arround.I was able to export BOM and Assembly file from gerbers but I am not sure about resizing. 

Wouldn't enlarging mess up with component locations/placements ?
