### ISSUE TITLE
Matrix Mixer

### ISSUE THREAD

**Issue by daltronbeats** [forestcaver/Analog-Voice#3]
Thanks for your work on this! Just building one now. I believe pin 1 is labelled incorrectly on the MM PCB idc10 power header? Can you confirm? 
Thanks

**Comment by forestcaver** [comment]
Yes! The bigger crime is it looks like I missed putting markers for -12v on the pcb that is uploaded - that is the more unforgivable act ! (Then the pin marking would not matter so much). Thanks. Will correct it.
