### ISSUE TITLE
Source files for the TZFM VCO

### ISSUE THREAD

**Issue by jimmerricks** [forestcaver/Analog-Voice#4]
Thank you for all of your wonderful designs. Is there any chance you plan to add the TZFM VCO source files to the repo? It looks like the perfect basic analogue voice and I'm keen to try my hand at a QFN chip.

**Comment by forestcaver** [comment]
Thanks for the kind works but no - no plans to add any more modules currently. I may decide to in the future...

**Comment by jimmerricks** [comment]
Thanks for the response. I wait with hope.
